# Generated by Django 5.2.17 on 2026-09-30 18:15

import django.db.models.deletion
import django.utils.timezone
import tenders.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('key', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=200)),
                ('help', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(max_length=60)),
                ('entity_type', models.CharField(blank=True, max_length=40)),
                ('entity_id', models.CharField(blank=True, max_length=40)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=250)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('prev_hash', models.CharField(blank=True, max_length=64)),
                ('hash', models.CharField(blank=True, max_length=64)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('REVISED', 'Revised'), ('WITHDRAWN', 'Withdrawn'), ('OPENED', 'Opened'), ('TECH_QUALIFIED', 'Technically qualified'), ('TECH_DISQUALIFIED', 'Technically disqualified'), ('SHORTLISTED', 'Shortlisted'), ('SELECTED', 'Selected'), ('NOT_SELECTED', 'Not selected')], default='SUBMITTED', max_length=20)),
                ('current_version', models.PositiveIntegerField(default=0)),
                ('receipt_no', models.CharField(blank=True, max_length=40)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bids', to='accounts.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='ComparativeStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending validation'), ('VALIDATED', 'Validated'), ('SUPERSEDED', 'Superseded')], default='PENDING', max_length=12)),
                ('fewer_than_three', models.BooleanField(default=False)),
                ('justification', models.TextField(blank=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_no', models.CharField(blank=True, max_length=30, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10)),
                ('attachment', models.FileField(blank=True, upload_to='notices/', validators=[tenders.validators.validate_upload])),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notices', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='INFO', max_length=30)),
                ('message', models.CharField(max_length=400)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StageForward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('TECHNICAL', 'Technical'), ('FINANCE', 'Finance'), ('CFO', 'CFO')], max_length=10)),
                ('round', models.PositiveIntegerField()),
                ('forwarded_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('reminded_at', models.DateTimeField(blank=True, null=True)),
                ('forwarded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['forwarded_at'],
            },
        ),
        migrations.CreateModel(
            name='StageDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='stage_docs/', validators=[tenders.validators.validate_upload])),
                ('forward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenders.stageforward')),
            ],
        ),
        migrations.CreateModel(
            name='StatementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('delivery_days', models.PositiveIntegerField(default=0)),
                ('validity_days', models.PositiveIntegerField(default=0)),
                ('tech_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenders.bid')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tenders.comparativestatement')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_no', models.CharField(blank=True, max_length=30, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=80)),
                ('description', models.TextField(verbose_name='Description / specification')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=14)),
                ('unit', models.CharField(default='Nos', max_length=30)),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(default='INR', max_length=5)),
                ('emd_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='EMD / security deposit')),
                ('eligibility', models.TextField(blank=True)),
                ('terms', models.TextField(blank=True, verbose_name='Payment & delivery terms / T&C')),
                ('evaluation_criteria', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('visibility', models.CharField(choices=[('OPEN', 'Open – all approved vendors'), ('LIMITED', 'Limited – invited vendors only')], default='OPEN', max_length=8)),
                ('bid_start_at', models.DateTimeField()),
                ('bid_end_at', models.DateTimeField()),
                ('opening_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('BIDDING_OPEN', 'Bidding open'), ('BIDDING_CLOSED', 'Bidding closed'), ('OPENED', 'Opened'), ('TECHNICAL_REVIEW', 'Technical review'), ('TECHNICAL_APPROVED', 'Technically approved'), ('FINANCE_REVIEW', 'Finance review'), ('QUOTATION_VALIDATION', 'Quotation validation'), ('CFO_REVIEW', 'CFO review'), ('APPROVED', 'Approved (award pending)'), ('AWARDED', 'Awarded'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected'), ('SENT_BACK', 'Sent back'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=22)),
                ('return_stage', models.CharField(blank=True, max_length=10)),
                ('status_reason', models.TextField(blank=True)),
                ('round', models.PositiveIntegerField(default=0)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenders_created', to=settings.AUTH_USER_MODEL)),
                ('notice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenders', to='tenders.notice')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualified', models.BooleanField()),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(auto_now=True)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='tenders.bid')),
                ('evaluated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='tenders.tender')),
            ],
        ),
        migrations.AddField(
            model_name='stageforward',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwards', to='tenders.tender'),
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='GENERAL', max_length=20)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('status', models.CharField(default='PENDING', max_length=10)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='tenders.tender')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Corrigendum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrigenda', to='tenders.tender')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='comparativestatement',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='tenders.tender'),
        ),
        migrations.AddField(
            model_name='bid',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='tenders.tender'),
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_value', models.DecimalField(decimal_places=2, max_digits=16)),
                ('justification', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('SENT', 'Email sent'), ('ACCEPTED', 'Accepted by vendor')], default='APPROVED', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.vendor')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenders.bid')),
                ('tender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='award', to='tenders.tender')),
            ],
        ),
        migrations.CreateModel(
            name='TenderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tender_docs/', validators=[tenders.validators.validate_upload])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenders.tender')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BidVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField()),
                ('encrypted_payload', models.TextField()),
                ('document', models.FileField(blank=True, upload_to='bid_docs/', validators=[tenders.validators.validate_upload])),
                ('emd_proof', models.FileField(blank=True, upload_to='bid_emd/', validators=[tenders.validators.validate_upload])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='tenders.bid')),
            ],
            options={
                'ordering': ['-version_no'],
                'unique_together': {('bid', 'version_no')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('tender', 'vendor')},
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('TECHNICAL', 'Technical'), ('FINANCE', 'Finance'), ('CFO', 'CFO')], max_length=10)),
                ('round', models.PositiveIntegerField()),
                ('decision', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('SEND_BACK', 'Send back for clarification')], max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='tenders.tender')),
            ],
            options={
                'ordering': ['decided_at'],
                'unique_together': {('tender', 'stage', 'round', 'approver')},
            },
        ),
        migrations.CreateModel(
            name='TenderInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='tenders.tender')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='accounts.vendor')),
            ],
            options={
                'unique_together': {('tender', 'vendor')},
            },
        ),
    ]
