# Generated by Django 4.2.7 on 2026-10-01 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_no', models.CharField(blank=True, max_length=30, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=80)),
                ('description', models.TextField(verbose_name='Product specification')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=14)),
                ('unit', models.CharField(default='Nos', max_length=30)),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(default='INR', max_length=5)),
                ('required_by', models.DateField(blank=True, null=True)),
                ('terms', models.TextField(blank=True, verbose_name='Delivery / purchase requirements')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('TENDERED', 'Tender generated')], default='SUBMITTED', max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tender', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisition', to='tenders.tender')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
