# Generated by Django 4.2.7 on 2026-10-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PO', 'Purchase Officer'), ('HOD', 'Head of Department'), ('TC', 'Technical Committee'), ('FC', 'Finance Committee'), ('CFO', 'CFO'), ('VENDOR', 'Vendor')], default='VENDOR', max_length=10),
        ),
    ]
